### ISSUE TITLE
Remove gun emoji

### ISSUE THREAD

**Issue by lemoness** [HabitRPG/habitica-markdown#1]
We had an issue with the gun emoji being used for a triggering message in one of the Guilds that deals with sensitive issues, and the mods have concluded that there's really no use for the gun emoji on the Habitica site. We can go ahead and remove it. 

We may want to also consider removing any emoji that reference alcohol and/or drugs, if any are currently supported.

**Comment by crookedneighbor** [comment]
Fixed.
