### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by paglias** [HabitRPG/habitica-markdown#88]

**Comment by benkelaar** [comment]
@paglias Are you looking in to this? 

I gave it a whirl locally and it's rather involved. I introduced babel to pre-compile the tests to allow them to specify dependencies as dictated by the new version of habitica-eslint-config, but I still get an `import/export should only be used in sourcetype: module` exception in the build phase. To fix this I think I can introduce bablify into the browserify step, but I see the habitica main module uses gulp to manage this, is this something that should be introduced here as well?

Should I create a draft pull request with how far I've gotten? (In the meanwhile you can see the changes I made here: https://github.com/benkelaar/habitica-markdown/commit/a3dd92bc418f7a792576a3af993121de45567440 )

**Comment by paglias** [comment]
@benkelaar I'm not and I don't think I'll have time in the near future, so this was more of a reference issue for two issues that can go separately:

1. [Code dependencies](https://github.com/HabitRPG/habitica-markdown/blob/master/package.json#L40-L43), mainly `markdown-it` modules which affect functionality - we should see if there's any breaking change
2. [Dev dependencies](https://github.com/HabitRPG/habitica-markdown/blob/master/package.json#L29-L37): external ones like mocha are quite old and should be upgraded but they'll have a ton of breaking changes and it's not super important given the low activity of this module. What I would like to upgrade are at least the eslint configs to use the most recent one of `eslint-config-habitrpg` so that the code style follows the main repo as much as possible. Our own config has a lot of es6+ code but transpilation using Babel shouldn't be necessary as nowadays browsers are quite up to date with the JS spec except for es6 modules, we should still use older `module.exports` style modules (commonjs)  

But your branch seems to tackle most issues, including babel transpilation so since it's done I'd include it if it doesn't require much extra work. I haven't tested it though. The only change I'd say is necessary is pointing the package.json main field to a transpiled version that doesn't use es6 modules (or go back to using module.exports here - might be easier - as they're not available in node 12 and the main repo babel config doesn't transpile external modules so using es6 modules won't work)

**Comment by benkelaar** [comment]
Yeah, that sounds like a good approach. I'll go back to the module.exports version and get rid of the babel transpilation again entirely.

After that I'll hook up a merge request and rebase the other branch on top of it.

**Comment by benkelaar** [comment]
Hmm, still having issues with uglify, which apparently doesn't support ES6 at all. Should I switch to   `terser-webpack-plugin` as [is being suggested here?](https://stackoverflow.com/a/53336031/446496)

Edit: Hmm, looking more at it, probably better to just use https://github.com/terser/terser directly

**Comment by paglias** [comment]
The magic world of JS tooling :/ 

Webpack is definitely an option (https://webpack.js.org/guides/author-libraries/) and in that case browserify can be removed. It's probably a bit more complex than terser but at least it wouldn't introduce a new tool since we use it to bundle the website as well.

**Comment by benkelaar** [comment]
Ah, I got it working now with terser, but I can see if I can switch it to webpack.

**Comment by benkelaar** [comment]
It's indeed a lot simpler with webpack, but I'm not quite sure I configured it correctly now. Will hold off on rebasing the other branch. (It doesn't necessarily need these changes so don't want to needlessly block that merge request)

**Comment by benkelaar** [comment]
Been reading up more on how all this works. 

@paglias Does using webpack mean we no longer need to support bower? The bower.json file was outdated anyway and the dist directory in source control was kinda freaking me out 😉 

You mentioned the CI/CD pipeline used to run on Travis but is now no longer running and we should set up github Actions instead. Is that something I can look in to? Would basically boil down to running `npm run test`, `TARGET_ENV=production npm run build` & `npm publish` in that order right? However does that mean we need to inject NPM credentials into the github actions somehow?

Edit: See setting up actions is collaborators only, so that's something you or someone else from HabitRPG should do. Will look in to dropping bower though.

**Comment by paglias** [comment]
Yeah bower is not really used anymore. As for the CI/CD pipeline there's a way to inject secrets like NPM credentials inside Github Actions in a way that makes sure they're not exposed publicly but I'd say for now we can skip the publish to npm part

**Comment by benkelaar** [comment]
Yeah, for a small library like this CI is much more important than CD anyway. Sounds good. 

Then I think the branch is set up correctly.

I only just noticed that it should be possible to run the tests through webpack as well and then we might be able to use ES6 modules after all.
